export const metadata = {
    title: "Projects || Portfolio Website",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({ children }) {
    return (
      <html className="scroll-smooth 2xl:text-2xl" lang="en">
        <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
          <meta name="description" content="This is a description of your site for SEO purposes." />
          <meta name="robots" content="index, follow" />
          <meta charSet="UTF-8" />
          <meta name="theme-color" content="#ffffff" />
          <link rel="icon" href="/favicon.ico" />
          <meta property="og:title" content="Portfolio Website " />
          <meta property="og:description" content="This is a description of your site for SEO purposes." />
          <meta property="og:type" content="website" />
          <meta property="og:url" content="https://www.yourwebsite.com/" />
          <meta property="og:image" content="https://www.yourwebsite.com/image.jpg" />
          <meta name="twitter:card" content="summary_large_image" />
          <meta name="twitter:title" content="Your React App" />
          <meta name="twitter:description" content="This is a description of your site for SEO purposes." />
          <meta name="twitter:image" content="https://www.yourwebsite.com/image.jpg" />
        </head>
        <body>{children}</body>
      </html>
    );
  }